feat: create new download command connected to new endpoint
biotia/geoseeq_api_client pull request #15
Opened 2023-07-07 17:43 UTC by tnemcsok

New download command (download files) currently just next to download sample-results. The command use the new server endpoint so generates only one request for fetching the download links and has the following new features:
- files can be filtered for a list of extensions
- group results can also be fetched with --folder-type = "all" or "project"
- Files can be downloaded with all previous versions or just the current
The generated file names have the following format:
{project_name}.{sample_name}.{folder_name}.{file_name}.{extension}   (without versions)
{project_name}.{sample_name}.{folder_name}.{file_name}.v{version_no}.{extension}.  (with versions)

All "." in entity names are replaced to "-" , "::" to "__" and invalid characters ([":", '"', "<", ">", "/", "\\", "|", "?"], maybe there are more actually...) to "-" on the server side.

Download commands will be displayed on the geoseeq FE to help users.

2023-07-18 12:23 UTC, dcdanko commented
I don’t think we need more info than that now but I could see a future where we want the entire stored info so we could (eg)
- grab a different linked file (like a BAM index)
- download differently based on storage type
- give a preview of the file sizes before initiating download

If/when we want to do stuff like this we can add `?verbose=true` or similar to the server side endpoint.

2023-07-18 12:28 UTC, dcdanko commented
Code looks good but I would like you to add a “preview” that shows the user what’s going to be downloaded before running the download (similar to the upload reads command) and asks the user to confirm. 

This should automatically accept if the user adds `--confirm` (or similar)

This only needs to show if we actually download file content, not just URLs.

2023-07-18 12:29 UTC, dcdanko requested changes
see preview comment

2023-07-25 09:23 UTC, tnemcsok commented
Confirmation has been added. Now it looks like this after the download command:
<img width="1116" alt="Screenshot 2023-07-25 at 11 20 19" src="https://github.com/biotia/geoseeq_api_client/assets/66177285/02d64058-4087-421d-baad-6f6b98ebd71b">

2023-08-10 17:49 UTC, merged